import { IsString, IsEnum } from 'class-validator';

export enum RelationshipType {
  // Original
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  SON = 'SON',
  DAUGHTER = 'DAUGHTER',
  BROTHER = 'BROTHER',
  SISTER = 'SISTER',
  HUSBAND = 'HUSBAND',
  WIFE = 'WIFE',
  GRANDFATHER = 'GRANDFATHER',
  GRANDMOTHER = 'GRANDMOTHER',
  GRANDSON = 'GRANDSON',
  GRANDDAUGHTER = 'GRANDDAUGHTER',
  UNCLE = 'UNCLE',
  AUNT = 'AUNT',
  COUSIN = 'COUSIN',

  // Blood relations
  PARENT = 'PARENT',
  CHILD = 'CHILD',
  SIBLING = 'SIBLING',
  GRANDPARENT = 'GRANDPARENT',
  GRANDCHILD = 'GRANDCHILD',
  GREAT_GRANDPARENT = 'GREAT_GRANDPARENT',
  GREAT_GRANDCHILD = 'GREAT_GRANDCHILD',

  // Marriage
  SPOUSE = 'SPOUSE',
  PARTNER = 'PARTNER',
  EX_SPOUSE = 'EX_SPOUSE',
  FIANCÉ = 'FIANCÉ',
  FIANCÉE = 'FIANCÉE',

  // Step relations
  STEP_FATHER = 'STEP_FATHER',
  STEP_MOTHER = 'STEP_MOTHER',
  STEP_PARENT = 'STEP_PARENT',
  STEP_SON = 'STEP_SON',
  STEP_DAUGHTER = 'STEP_DAUGHTER',
  STEP_CHILD = 'STEP_CHILD',
  STEP_BROTHER = 'STEP_BROTHER',
  STEP_SISTER = 'STEP_SISTER',
  STEP_SIBLING = 'STEP_SIBLING',

  // Adoption
  ADOPTIVE_FATHER = 'ADOPTIVE_FATHER',
  ADOPTIVE_MOTHER = 'ADOPTIVE_MOTHER',
  ADOPTIVE_PARENT = 'ADOPTIVE_PARENT',
  ADOPTIVE_SON = 'ADOPTIVE_SON',
  ADOPTIVE_DAUGHTER = 'ADOPTIVE_DAUGHTER',
  ADOPTIVE_CHILD = 'ADOPTIVE_CHILD',

  // Foster
  FOSTER_FATHER = 'FOSTER_FATHER',
  FOSTER_MOTHER = 'FOSTER_MOTHER',
  FOSTER_PARENT = 'FOSTER_PARENT',
  FOSTER_SON = 'FOSTER_SON',
  FOSTER_DAUGHTER = 'FOSTER_DAUGHTER',
  FOSTER_CHILD = 'FOSTER_CHILD',

  // Legal
  GUARDIAN = 'GUARDIAN',
  WARD = 'WARD',
  LEGAL_FATHER = 'LEGAL_FATHER',
  LEGAL_MOTHER = 'LEGAL_MOTHER',
  LEGAL_GUARDIAN = 'LEGAL_GUARDIAN',

  // Birth
  SURROGATE = 'SURROGATE',
  SURROGATE_CHILD = 'SURROGATE_CHILD',
  SURROGATE_MOTHER = 'SURROGATE_MOTHER',

  // Multiple birth
  TWIN = 'TWIN',
  TRIPLET = 'TRIPLET',
  QUADRUPLET = 'QUADRUPLET',

  // Extended family
  NEPHEW = 'NEPHEW',
  NIECE = 'NIECE',
  GREAT_UNCLE = 'GREAT_UNCLE',
  GREAT_AUNT = 'GREAT_AUNT',
  FIRST_COUSIN = 'FIRST_COUSIN',
  SECOND_COUSIN = 'SECOND_COUSIN',
  THIRD_COUSIN = 'THIRD_COUSIN',
  COUSIN_ONCE_REMOVED = 'COUSIN_ONCE_REMOVED',
  COUSIN_TWICE_REMOVED = 'COUSIN_TWICE_REMOVED',

  // Divorce/Widow
  DIVORCED = 'DIVORCED',
  DIVORCED_FROM = 'DIVORCED_FROM',
  WIDOW = 'WIDOW',
  WIDOWER = 'WIDOWER',
  EX_HUSBAND = 'EX_HUSBAND',
  EX_WIFE = 'EX_WIFE',

  // Genetics
  HALF_BROTHER = 'HALF_BROTHER',
  HALF_SISTER = 'HALF_SISTER',
  HALF_SIBLING = 'HALF_SIBLING',

  // In-laws
  FATHER_IN_LAW = 'FATHER_IN_LAW',
  MOTHER_IN_LAW = 'MOTHER_IN_LAW',
  BROTHER_IN_LAW = 'BROTHER_IN_LAW',
  SISTER_IN_LAW = 'SISTER_IN_LAW',
  SON_IN_LAW = 'SON_IN_LAW',
  DAUGHTER_IN_LAW = 'DAUGHTER_IN_LAW',

  // God family
  GODFATHER = 'GODFATHER',
  GODMOTHER = 'GODMOTHER',
  GODSON = 'GODSON',
  GODDAUGHTER = 'GODDAUGHTER',

  // Unknown
  UNKNOWN = 'UNKNOWN',
  CUSTOM = 'CUSTOM',
}

export class CreateRelationshipDto {
  @IsString()
  fromMemberId: string;

  @IsString()
  toMemberId: string;

  @IsEnum(RelationshipType)
  type: RelationshipType;
}
